name: CICD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: first down the docker-compose
        run: docker-compose down
      - name: then up the docker-compose
        run: docker-compose up -d
